### ISSUE TITLE
Cannot use the Orb in Alpine image

### ISSUE THREAD

**Issue by moorara** [iynere/compare-url-orb#18]
### Orb version

`0.4.9`

### What happened

When using the `reconstruct` job in `alpine` image, whih doesn't have `bash`, the job cannot complete due to the following error:

```
sh: missing ]]
```

### Expected behavior

The script inside the job should be re-written for `shell`. You can use `shellcheck` to make sure it is compatible with standard versions of `sh`.

**Comment by sibelius** [comment]
can you provide your circleci config?

it is working fine in `1.0.2`

**Comment by moos3** [comment]
I'm having the same issues with 1.2.0 

```
sh: missing ]]
```

We are trying to use it in an environment that uses the following circleci configuration.

```
version: 2.1

orbs:
  circle-compare-url: iynere/compare-url@1.2.0

references:
  setup_docker: &setup_docker
    setup_remote_docker:
      version: 18.06.0-ce

  add_curl: &add_curl
    run:
      command: |
          apk update && apk add --no-cache curl curl-dev bash

  # These are duplicated because of a CircleCI limitation
  # https://circleci.com/docs/2.0/caching/#restoring-cache
  restore_gateway_cache: &restore_gateway_cache
    restore_cache:
      keys:
        - gateway-{{ .Branch }}-{{ .Revision }}
        - gateway-{{ .Branch }}
        - gateway

  save_gateway_cache: &save_gateway_cache
    save_cache:
      key: gateway-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/cache/gateway.tar

  restore_org_cache: &restore_org_cache
    restore_cache:
      keys:
        - org-{{ .Branch }}-{{ .Revision }}
        - org-{{ .Branch }}
        - org

  save_org_cache: &save_org_cache
    save_cache:
      key: org-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/cache/org.tar

  restore_continuum_cache: &restore_continuum_cache
    restore_cache:
      keys:
        - continuum-{{ .Branch }}-{{ .Revision }}
        - continuum-{{ .Branch }}
        - continuum

  save_continuum_cache: &save_continuum_cache
    save_cache:
      key: continuum-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/cache/continuum.tar

  default_env: &default_env
    ORG: moos3
    REPO: teams

  defaults: &defaults
    docker:
      - image: docker:stable-git
    environment: *default_env
    working_directory: ~/projects

  run_on_all_tags: &run_on_all_tags
    filters:
      tags:
        only: /.*/

  # Needs to be one step because of the conditional
  conditional_build_and_push: &conditional_build_and_push
    run:
      name: Build and push if this repo has changed
      command: |

        if [ -n "$CIRCLE_TAG" ] || scripts/check_subrepo_changed.sh $CIRCLE_COMPARE_URL $PROJECT; then
          DOCKER_REPO="$ORG/$PROJECT";
          SHORT_COMMIT=`git rev-parse --short HEAD`

          if [ -f ~/cache/$PROJECT.tar ]; then
            docker load -i ~/cache/$PROJECT.tar
          fi

          docker build --cache-from=$PROJECT \
          --build-arg NPM_TOKEN=$NPM_TOKEN \
          -f $PROJECT/Dockerfile \
          -t $PROJECT .;

          docker run $PROJECT sh -c "npm install --only=dev && npm test";

          tag_image () {
            local tag="$DOCKER_REPO:$1"
            echo Tagging image $PROJECT as $tag
            docker tag $PROJECT $tag
          }

          # Push tag name, or branch name if tag doesn't exist (CircleCI runs tags/branches separately)
          tag_image "${CIRCLE_TAG:-$CIRCLE_BRANCH}"
          [ -n "$CIRCLE_BRANCH" ] && tag_image $CIRCLE_BRANCH-$SHORT_COMMIT
          [ -n "$CIRCLE_TAG" ] && tag_image rc-$CIRCLE_TAG
          [ $CIRCLE_BRANCH == "staging" ] && tag_image stg-$SHORT_COMMIT
          docker login -u $DOCKER_USERNAME -p $DOCKER_SECURE_PASS
          docker push $DOCKER_REPO

          mkdir -p ~/cache;
          docker save $PROJECT -o ~/cache/$PROJECT.tar;
        else
          echo "No changes detected in $PROJECT";
        fi

jobs:
  org:
    <<: *defaults
    environment:
      <<: *default_env
      PROJECT: org
    steps:
      - checkout
      - *setup_docker
      - *add_curl
      - *restore_org_cache
      - circle-compare-url/reconstruct
      - circle-compare-url/use
      - *conditional_build_and_push
      - *save_org_cache

  continuum:
    <<: *defaults
    environment:
      <<: *default_env
      PROJECT: continuum
    steps:
      - checkout
      - *setup_docker
      - *add_curl
      - *restore_continuum_cache
      - circle-compare-url/reconstruct
      - circle-compare-url/use
      - *conditional_build_and_push
      - *save_continuum_cache

  gateway:
    <<: *defaults
    environment:
      <<: *default_env
      PROJECT: gateway
    steps:
      - checkout
      - *setup_docker
      - *add_curl
      - *restore_gateway_cache
      - circle-compare-url/reconstruct
      - circle-compare-url/use
      - *conditional_build_and_push
      - *save_gateway_cache

workflows:
  version: 2

  build_test_push:
    jobs:
      - gateway:
          <<: *run_on_all_tags
          context: org-global
      - continuum:
          <<: *run_on_all_tags
          context: org-global
      - org:
          <<: *run_on_all_tags
          context: org-global
```
